name: drug-gene-cdss
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pyg
  - rdkit
  - biopython
  - transformers
  - sentencepiece
  - scikit-learn
  - pandas
  - matplotlib
  - seaborn
  - tqdm
  - deepchem
  - captum
  - pyyaml
  - streamlit
  - requests
  - pip:
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-geometric