paths:
  data_dir: "data/"
  cache_dir: "cache/"
  output_dir: "results/"
  checkpoint_dir: "checkpoints/"
  relationships_file: "relationships.tsv"
  explanation_dir: "explanations/"  
  literature_cache: "cache/pubmed/"  

filter_settings:
  filter_genes_only: true
  filter_chemicals_only: true

model:
  protein_model_name: "facebook/esm2_t12_35M_UR50D"
  drug_node_dim: 16
  drug_edge_dim: 8
  drug_hidden_dim: 128
  drug_output_dim: 256
  egnn_num_layers: 4
  protein_embedding_dim: 480
  protein_freeze_layers: 6
  attention_heads: 8
  attention_dim: 256
  mlp_hidden_dims: [512, 256, 128]
  dropout_rate: 0.3
  model_weights: "checkpoints/best_model.pt"  # NEW

training:
  device: "cuda"
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.0001
  num_epochs: 30
  early_stopping_patience: 7
  gradient_clip: 1.0

data_split:
  train_size: 0.70
  test_size: 0.20
  val_size: 0.10

processing:
  max_protein_length: 1024
  use_scaffold_split: true
  max_conformers: 1
  conformer_optimize_steps: 200
  mc_dropout_samples: 20

# NEW: Explainability Configuration
explainability:
  enable_integrated_gradients: true
  ig_steps: 50
  ig_baseline_strategy: "zero"  # zero, gaussian, uniform
  use_generative_explanations: true
  generative_model: "google/flan-t5-base"
  generative_max_length: 250
  visualization_dpi: 300
  colormap: "plasma"

# NEW: Agentic AI Configuration
agent:
  llm_provider: "google"  # google, openai
  llm_model: "gemini-1.5-pro-latest"
  temperature: 0.0
  max_iterations: 15
  enable_pubmed_search: true
  max_papers_per_query: 5
  enable_molecular_reasoning: true
  enable_clinical_context: true

# NEW: PubMed API Configuration
pubmed:
  base_url: "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/"
  email: "faaiz.ds24@duk.ac.in"  
  api_key: "1ed2a4f8626f38b2bccb05b499bc8ad54009"  
  max_retries: 3
  cache_expiry_days: 30
